import { Connection, PublicKey, SystemProgram } from '@solana/web3.js'
import { AnchorWallet } from '@solana/wallet-adapter-react'
import { AnchorProvider, Program, BN } from '@coral-xyz/anchor'
import { toast } from 'sonner'
import { PROGRAM_IDS, CLUSTER } from '../programs/constants'
import { deriveUserStatePDA } from '../programs/pdas'
import complianceIdl from '../idl/compliance.json'

/**
 * Initialize user compliance state (must be called before KYC verification)
 */
export async function initializeUser(
  connection: Connection,
  wallet: AnchorWallet
) {
  try {
    const provider = new AnchorProvider(connection, wallet, { commitment: 'confirmed' })
    const program = new Program(complianceIdl as any, PROGRAM_IDS.compliance, provider)

    const [userStatePDA] = deriveUserStatePDA(wallet.publicKey)

    // Check if already initialized
    try {
      await program.account.userState.fetch(userStatePDA)
      return { success: true, alreadyInitialized: true }
    } catch {
      // Not initialized, proceed
    }

    const tx = await program.methods
      .initializeUser()
      .accounts({
        userState: userStatePDA,
        user: wallet.publicKey,
        systemProgram: SystemProgram.programId,
      })
      .rpc()

    return { success: true, signature: tx }
  } catch (error: any) {
    console.error('Initialize user error:', error)
    throw error
  }
}

/**
 * Verify KYC with zero-knowledge proof
 * @param connection Solana connection
 * @param wallet User's wallet
 * @param proofData ZK proof data (in production, this would be generated by a ZK circuit)
 */
export async function verifyKyc(
  connection: Connection,
  wallet: AnchorWallet,
  proofData?: Uint8Array
) {
  try {
    toast.loading('Verifying KYC...')

    const provider = new AnchorProvider(connection, wallet, { commitment: 'confirmed' })
    const program = new Program(complianceIdl as any, PROGRAM_IDS.compliance, provider)

    // 1. Ensure user state is initialized
    await initializeUser(connection, wallet)

    // 2. Derive user state PDA
    const [userStatePDA] = deriveUserStatePDA(wallet.publicKey)

    // 3. Generate mock ZK proof (in production, use actual ZK circuit)
    const mockProof = proofData || Buffer.from(new Array(64).fill(0).map(() => Math.floor(Math.random() * 256)))

    // KYC expiry: 1 year from now
    const expiry = new BN(Math.floor(Date.now() / 1000) + 365 * 24 * 60 * 60)

    // 4. Build verify_kyc instruction
    const tx = await program.methods
      .verifyKyc(Array.from(mockProof), expiry)
      .accounts({
        userState: userStatePDA,
        user: wallet.publicKey,
      })
      .rpc()

    toast.success('KYC Verified!', {
      description: 'Your identity has been verified with zero-knowledge proofs',
      action: {
        label: 'View on Explorer',
        onClick: () => window.open(`https://explorer.solana.com/tx/${tx}?cluster=${CLUSTER}`, '_blank')
      }
    })

    return { success: true, signature: tx }
  } catch (error: any) {
    console.error('KYC verification error:', error)
    toast.error('KYC verification failed', {
      description: error.message || 'Transaction failed'
    })
    throw error
  }
}

/**
 * Perform KYT check before transaction
 * @param connection Solana connection
 * @param wallet User's wallet
 * @param amount Transaction amount (in lamports)
 * @param recipient Recipient address
 */
export async function checkKyt(
  connection: Connection,
  wallet: AnchorWallet,
  amount: number,
  recipient: PublicKey
) {
  try {
    const provider = new AnchorProvider(connection, wallet, { commitment: 'confirmed' })
    const program = new Program(complianceIdl as any, PROGRAM_IDS.compliance, provider)

    // 1. Derive user state PDA
    const [userStatePDA] = deriveUserStatePDA(wallet.publicKey)

    // 2. Call kyt_check instruction
    const amountBN = new BN(amount)

    const tx = await program.methods
      .kytCheck(amountBN, recipient)
      .accounts({
        userState: userStatePDA,
        user: wallet.publicKey,
      })
      .rpc()

    // 3. Fetch updated risk score
    const userState = await program.account.userState.fetch(userStatePDA)
    const riskScore = userState.riskScore

    if (riskScore > 60) {
      toast.error('Transaction blocked', {
        description: `High risk score: ${riskScore}. Contact compliance team.`
      })
      return { success: false, riskScore, signature: tx }
    }

    return { success: true, riskScore, signature: tx }
  } catch (error: any) {
    console.error('KYT check error:', error)
    throw error
  }
}

/**
 * Generate Travel Rule payload for transfers >$3K
 * @param connection Solana connection
 * @param wallet User's wallet
 * @param amount Transaction amount in USD (lamports with 6 decimals)
 * @param recipient Recipient public key
 */
export async function generateTravelRulePayload(
  connection: Connection,
  wallet: AnchorWallet,
  amount: number,
  recipient: PublicKey
) {
  try {
    // Check if Travel Rule applies (>$3000)
    if (amount < 3000 * 1_000_000) {
      return { required: false }
    }

    toast.loading('Generating Travel Rule payload...')

    const provider = new AnchorProvider(connection, wallet, { commitment: 'confirmed' })
    const program = new Program(complianceIdl as any, PROGRAM_IDS.compliance, provider)

    // 1. Derive PDAs
    const [senderStatePDA] = deriveUserStatePDA(wallet.publicKey)
    const [recipientStatePDA] = deriveUserStatePDA(recipient)

    // 2. Call generate_travel_rule_payload instruction
    const amountBN = new BN(amount)

    const tx = await program.methods
      .generateTravelRulePayload(amountBN)
      .accounts({
        senderState: senderStatePDA,
        recipientState: recipientStatePDA,
        sender: wallet.publicKey,
      })
      .rpc()

    toast.success('Travel Rule payload generated', {
      description: 'Encrypted compliance data attached to transaction'
    })

    return {
      required: true,
      payload: tx, // In production, this would be encrypted payload data
      success: true,
      signature: tx
    }
  } catch (error: any) {
    console.error('Travel Rule generation error:', error)
    toast.error('Failed to generate Travel Rule payload', {
      description: error.message || 'Generation failed'
    })
    throw error
  }
}
